<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TouchChanX.Persistence\TouchChanX.Persistence.csproj" />
    <PackageReference Include="CalcBinding" />
    <PackageReference Include="R3" />
    <PackageReference Include="R3Extensions.ObservableEvents.SourceGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

</Project>
