<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ApplicationManifest>../app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Input.Stylus.DisableStylusAndTouchSupport" Value="true" />
    <RuntimeHostConfigurationOption Include="Switch.System.Winkdows.Input.Stylus.EnablePointerSupport" Value="true" />
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Media.EnableHardwareAccelerationInRdp" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TouchChanX.WPF\TouchChanX.WPF.csproj" />
  </ItemGroup>

</Project>
