<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ApplicationManifest>../app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <PublishAot>true</PublishAot>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <!--<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>-->
  </PropertyGroup>
  
  <ItemGroup>
    <ApplicationDefinition Include="WinUIApp.xaml" />
    <Page Remove="WinUIApp.xaml" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="assets\touchchan_hires.png" LogicalName="TouchChanX.touchchan_hires.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TouchChanX.SplashScreenGdiPlus\TouchChanX.SplashScreenGdiPlus.csproj" />
    <ProjectReference Include="..\TouchChanX.Win32\TouchChanX.Win32.csproj" />
    <ProjectReference Include="..\TouchChanX.WinUI\TouchChanX.WinUI.csproj" />
  </ItemGroup>

</Project>
