<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Platforms>x86;x64;ARM64</Platforms>
    <!-- 确保在类库项目 xaml 文件修改后重新编译 -->
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Animations" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.AI.MachineLearning" ExcludeAssets="All" />
    <PackageReference Include="Microsoft.Web.WebView2" ExcludeAssets="All" />
    <PackageReference Include="R3" />
    <PackageReference Include="R3Extensions.ObservableEvents.SourceGenerator" />
  </ItemGroup>

</Project>