<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <UseUwp>true</UseUwp>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PublishAot>true</PublishAot>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableMsixTooling>true</EnableMsixTooling>
    <!-- 忽视隐式继承警告 -->
    <NoWarn>$(NoWarn);NETSDK1023</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Uwp.Controls.SettingsControls" />
    <PackageReference Include="Kumo.Uwp.NavigationView.RailStyle" />
    <PackageReference Include="Microsoft.UI.Xaml" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="R3Extensions.AotCompatible" />
    <PackageReference Include="R3Extensions.ObservableEvents.SourceGenerator" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" ExcludeAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TouchChanX.Persistence\TouchChanX.Persistence.csproj" />
  </ItemGroup>

</Project>
