<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ApplicationManifest>../app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <!-- https://github.com/Sergio0694/ComputeSharp/blob/c3e9ad/samples/Directory.Build.props#L19 -->
    <NoWarn>$(NoWarn);WMC1006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TouchChanX.Persistence\TouchChanX.Persistence.csproj" />
    <ProjectReference Include="..\TouchChanX.WinUI\TouchChanX.WinUI.csproj" />
  </ItemGroup>

</Project>
